[package]
name = "rolls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha256 = "1.5.0"
hex = "0.4.3"
num = "0.4.1"
digest = "0.10.3"
